spring.application.name=golf

spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.url=${DATASOURCE_URL}

okta.oauth2.issuer=${AUTH0_ISSUER_URL}
okta.oauth2.audience=${AUTH0_AUDIENCE}

springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/v1/api-docs/swagger-ui/index.html

logging.level.com.alimmit.golf=debug