services:

  postgres:
    image: postgres:18.1
    container_name: golf-postgres
    ports:
      - "9876:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql

  golf-api:
    profiles: [app]
    image: golf-api:latest
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/golf

volumes:
  postgres:
