services:

  postgres:
    image: postgres:18.1
    container_name: golf-postgres
    ports:
      - "9876:5432"
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql

volumes:
  postgres: