#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_DIR="$SCRIPT_DIR/../.local"

# Import public environment variables
source "$LOCAL_DIR/.env.public"

# Start docker services to support local development
docker-compose -f "$LOCAL_DIR/docker-compose.yaml" up -d

# Start Spring Boot application
"$SCRIPT_DIR/mvnw" spring-boot:run -Dspring-boot.run.profiles=local
